unbind C-b
set-option -g prefix C-a
bind-key C-a send-prefix

bind | split-window -h
bind - split-window -v
unbind '"'
unbind %

bind r source-file ~/.tmux.conf

set-option -g status-position top
set -g status-right '#[fg=color249]#(date +"%I:%M%p %m-%d-%Y")#[default]'

set-option -g status-bg color233
set-option -g status-fg color249
set -g mode-style "fg=color0,bg=color11"
set -g pane-active-border-style 'fg=color238'
set -g pane-border-style 'fg=color236'
